package pojos;
// Generated Jul 17, 2020 7:25:23 PM by Hibernate Tools 4.3.1



/**
 * Film generated by hbm2java
 */
public class Film  implements java.io.Serializable {


     private int filmid;
     private String name;
     private String director;
     private String actor;
     private String runtime;
     private Integer delornot;

    public Film() {
    }

	
    public Film(int filmid) {
        this.filmid = filmid;
    }
    public Film(int filmid, String name, String director, String actor, String runtime, Integer delornot) {
       this.filmid = filmid;
       this.name = name;
       this.director = director;
       this.actor = actor;
       this.runtime = runtime;
       this.delornot = delornot;
    }
   
    public int getFilmid() {
        return this.filmid;
    }
    
    public void setFilmid(int filmid) {
        this.filmid = filmid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public String getActor() {
        return this.actor;
    }
    
    public void setActor(String actor) {
        this.actor = actor;
    }
    public String getRuntime() {
        return this.runtime;
    }
    
    public void setRuntime(String runtime) {
        this.runtime = runtime;
    }
    public Integer getDelornot() {
        return this.delornot;
    }
    
    public void setDelornot(Integer delornot) {
        this.delornot = delornot;
    }




}


