package pojos;
// Generated Jul 17, 2020 7:25:23 PM by Hibernate Tools 4.3.1



/**
 * FilmGen generated by hbm2java
 */
public class FilmGen  implements java.io.Serializable {


     private int id;
     private String filmid;
     private String genre;

    public FilmGen() {
    }

	
    public FilmGen(int id) {
        this.id = id;
    }
    public FilmGen(int id, String filmid, String genre) {
       this.id = id;
       this.filmid = filmid;
       this.genre = genre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFilmid() {
        return this.filmid;
    }
    
    public void setFilmid(String filmid) {
        this.filmid = filmid;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }




}


