package pojos;
// Generated Jul 17, 2020 7:25:23 PM by Hibernate Tools 4.3.1



/**
 * Purchesedfilm generated by hbm2java
 */
public class Purchesedfilm  implements java.io.Serializable {


     private int id;
     private String userid;
     private String filmid;

    public Purchesedfilm() {
    }

	
    public Purchesedfilm(int id) {
        this.id = id;
    }
    public Purchesedfilm(int id, String userid, String filmid) {
       this.id = id;
       this.userid = userid;
       this.filmid = filmid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getFilmid() {
        return this.filmid;
    }
    
    public void setFilmid(String filmid) {
        this.filmid = filmid;
    }




}


