package pojos;
// Generated Jul 17, 2020 7:25:23 PM by Hibernate Tools 4.3.1



/**
 * Ratings generated by hbm2java
 */
public class Ratings  implements java.io.Serializable {


     private int ratingid;
     private String userid;
     private String rating;
     private Integer delornot;

    public Ratings() {
    }

	
    public Ratings(int ratingid) {
        this.ratingid = ratingid;
    }
    public Ratings(int ratingid, String userid, String rating, Integer delornot) {
       this.ratingid = ratingid;
       this.userid = userid;
       this.rating = rating;
       this.delornot = delornot;
    }
   
    public int getRatingid() {
        return this.ratingid;
    }
    
    public void setRatingid(int ratingid) {
        this.ratingid = ratingid;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }
    public Integer getDelornot() {
        return this.delornot;
    }
    
    public void setDelornot(Integer delornot) {
        this.delornot = delornot;
    }




}


