package pojos;
// Generated Jul 17, 2020 7:25:23 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userid;
     private String name;
     private String password;
     private String role;

    public Users() {
    }

	
    public Users(int userid, String name) {
        this.userid = userid;
        this.name = name;
    }
    public Users(int userid, String name, String password, String role) {
       this.userid = userid;
       this.name = name;
       this.password = password;
       this.role = role;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


